[build.processing]
  skip_processing = true
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.images]
  compress = false  # <--- Désactive la compression d'image ici